### ISSUE TITLE
Does it support with sql input?

### ISSUE THREAD

**Issue by agusmakmun** [andersinno/python-database-sanitizer#21]
For example

```
$ database-sanitizer my-db.sql > output.sql  # mysql db
```

Or 

```
$ database-sanitizer my-db.psql.gz > output.psql.gz     # compression
$ database-sanitizer my-db.psql > output.psql           # default postgre
```

**Comment by suutari-ai** [comment]
Sorry, but the input cannot be read from a file currently, but must come through a database connection. Support for sanitizing a SQL dump file would be a great feature though. So PRs are wellcome! :slightly_smiling_face:

**Comment by JsseL** [comment]
I'll close the issue for now. 💯 points to whom makes the feature happen.
